//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_serialization.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#include "duckdb/common/serializer/serializer.hpp"
#include "duckdb/common/serializer/deserializer.hpp"
#include "duckdb/storage/wal_entry.hpp"

namespace duckdb {

void WALCheckpoint::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<MetaBlockPointer>(101, "meta_block", meta_block);
}

WALCheckpoint WALCheckpoint::Deserialize(Deserializer &deserializer) {
	WALCheckpoint result;
	deserializer.ReadProperty<MetaBlockPointer>(101, "meta_block", result.meta_block);
	return result;
}

void WALCreateMacro::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "macro", macro);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "macro", macro);
	}
}

WALCreateMacro WALCreateMacro::Deserialize(Deserializer &deserializer) {
	WALCreateMacro result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "macro", result.macro);
	return result;
}

void WALCreateSchema::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", schema);
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(102, "qualified_name", qualified_name, QualifiedName());
	}
}

WALCreateSchema WALCreateSchema::Deserialize(Deserializer &deserializer) {
	WALCreateSchema result;
	deserializer.ReadPropertyWithDefault<Identifier>(101, "schema", result.schema);
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(102, "qualified_name", result.qualified_name, QualifiedName());
	return result;
}

void WALCreateSequence::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "sequence", sequence);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "sequence", sequence);
	}
}

WALCreateSequence WALCreateSequence::Deserialize(Deserializer &deserializer) {
	WALCreateSequence result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "sequence", result.sequence);
	return result;
}

void WALCreateTable::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "table", table);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "table", table);
	}
}

WALCreateTable WALCreateTable::Deserialize(Deserializer &deserializer) {
	WALCreateTable result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "table", result.table);
	return result;
}

void WALCreateTableMacro::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "table_macro", table_macro);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "table_macro", table_macro);
	}
}

WALCreateTableMacro WALCreateTableMacro::Deserialize(Deserializer &deserializer) {
	WALCreateTableMacro result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "table_macro", result.table_macro);
	return result;
}

void WALCreateTrigger::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "trigger", trigger);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "trigger", trigger);
	}
}

WALCreateTrigger WALCreateTrigger::Deserialize(Deserializer &deserializer) {
	WALCreateTrigger result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "trigger", result.trigger);
	return result;
}

void WALCreateType::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "type", type);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "type", type);
	}
}

WALCreateType WALCreateType::Deserialize(Deserializer &deserializer) {
	WALCreateType result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "type", result.type);
	return result;
}

void WALCreateView::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "view", view);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "view", view);
	}
}

WALCreateView WALCreateView::Deserialize(Deserializer &deserializer) {
	WALCreateView result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "view", result.view);
	return result;
}

void WALDropIndex::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
}

WALDropIndex WALDropIndex::Deserialize(Deserializer &deserializer) {
	WALDropIndex result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropMacro::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
}

WALDropMacro WALDropMacro::Deserialize(Deserializer &deserializer) {
	WALDropMacro result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropSchema::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", schema);
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(102, "qualified_name", qualified_name, QualifiedName());
	}
}

WALDropSchema WALDropSchema::Deserialize(Deserializer &deserializer) {
	WALDropSchema result;
	deserializer.ReadPropertyWithDefault<Identifier>(101, "schema", result.schema);
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(102, "qualified_name", result.qualified_name, QualifiedName());
	return result;
}

void WALDropSequence::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
}

WALDropSequence WALDropSequence::Deserialize(Deserializer &deserializer) {
	WALDropSequence result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropTable::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
}

WALDropTable WALDropTable::Deserialize(Deserializer &deserializer) {
	WALDropTable result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropTableMacro::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
}

WALDropTableMacro WALDropTableMacro::Deserialize(Deserializer &deserializer) {
	WALDropTableMacro result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropTrigger::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	serializer.WritePropertyWithDefault<Identifier>(103, "table", table);
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(104, "qualified_name", qualified_name, QualifiedName());
	}
}

WALDropTrigger WALDropTrigger::Deserialize(Deserializer &deserializer) {
	WALDropTrigger result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithDefault<Identifier>(103, "table", result.table);
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(104, "qualified_name", result.qualified_name, QualifiedName());
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropType::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
}

WALDropType WALDropType::Deserialize(Deserializer &deserializer) {
	WALDropType result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropView::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
}

WALDropView WALDropView::Deserialize(Deserializer &deserializer) {
	WALDropView result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALReclusterDeleteEntry::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<persistent_table_id_t>(101, "table_id", table_id);
	serializer.WriteProperty<recluster_task_id_t>(102, "task_id", task_id);
	serializer.WritePropertyWithDefault<uint32_t>(103, "chunk_index", chunk_index);
	serializer.WritePropertyWithDefault<vector<row_t>>(104, "new_rowids", new_rowids);
}

WALReclusterDeleteEntry WALReclusterDeleteEntry::Deserialize(Deserializer &deserializer) {
	WALReclusterDeleteEntry result;
	deserializer.ReadProperty<persistent_table_id_t>(101, "table_id", result.table_id);
	deserializer.ReadProperty<recluster_task_id_t>(102, "task_id", result.task_id);
	deserializer.ReadPropertyWithDefault<uint32_t>(103, "chunk_index", result.chunk_index);
	deserializer.ReadPropertyWithDefault<vector<row_t>>(104, "new_rowids", result.new_rowids);
	return result;
}

void WALReclusterEntry::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<persistent_table_id_t>(101, "table_id", table_id);
	serializer.WriteProperty<recluster_task_id_t>(102, "task_id", task_id);
	serializer.WriteProperty<layout_version_t>(103, "expected_layout_version", expected_layout_version);
	serializer.WriteProperty<layout_version_t>(104, "target_layout_version", target_layout_version);
	serializer.WriteProperty<row_t>(105, "range_start", range_start);
	serializer.WriteProperty<row_t>(106, "range_end", range_end);
	serializer.WriteProperty<MetaBlockPointer>(107, "manifest_pointer", manifest_pointer);
	serializer.WritePropertyWithDefault<uint64_t>(108, "manifest_size", manifest_size);
	serializer.WritePropertyWithDefault<uint64_t>(109, "manifest_checksum", manifest_checksum);
	serializer.WriteProperty<delete_sequence_t>(110, "journal_resolved_through", journal_resolved_through);
	serializer.WritePropertyWithDefault<uint64_t>(111, "final_delete_row_count", final_delete_row_count);
	serializer.WritePropertyWithDefault<uint32_t>(112, "delete_chunk_count", delete_chunk_count);
}

WALReclusterEntry WALReclusterEntry::Deserialize(Deserializer &deserializer) {
	WALReclusterEntry result;
	deserializer.ReadProperty<persistent_table_id_t>(101, "table_id", result.table_id);
	deserializer.ReadProperty<recluster_task_id_t>(102, "task_id", result.task_id);
	deserializer.ReadProperty<layout_version_t>(103, "expected_layout_version", result.expected_layout_version);
	deserializer.ReadProperty<layout_version_t>(104, "target_layout_version", result.target_layout_version);
	deserializer.ReadProperty<row_t>(105, "range_start", result.range_start);
	deserializer.ReadProperty<row_t>(106, "range_end", result.range_end);
	deserializer.ReadProperty<MetaBlockPointer>(107, "manifest_pointer", result.manifest_pointer);
	deserializer.ReadPropertyWithDefault<uint64_t>(108, "manifest_size", result.manifest_size);
	deserializer.ReadPropertyWithDefault<uint64_t>(109, "manifest_checksum", result.manifest_checksum);
	deserializer.ReadProperty<delete_sequence_t>(110, "journal_resolved_through", result.journal_resolved_through);
	deserializer.ReadPropertyWithDefault<uint64_t>(111, "final_delete_row_count", result.final_delete_row_count);
	deserializer.ReadPropertyWithDefault<uint32_t>(112, "delete_chunk_count", result.delete_chunk_count);
	return result;
}

void WALSequenceValue::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<uint64_t>(103, "usage_count", usage_count);
	} else {
		serializer.WriteProperty<uint64_t>(103, "usage_count", usage_count);
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<int64_t>(104, "counter", counter);
	} else {
		serializer.WriteProperty<int64_t>(104, "counter", counter);
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<optional<int64_t>>(105, "last_value", last_value);
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(106, "qualified_name", qualified_name, QualifiedName());
	}
}

WALSequenceValue WALSequenceValue::Deserialize(Deserializer &deserializer) {
	WALSequenceValue result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithDefault<uint64_t>(103, "usage_count", result.usage_count);
	deserializer.ReadPropertyWithDefault<int64_t>(104, "counter", result.counter);
	deserializer.ReadPropertyWithDefault<optional<int64_t>>(105, "last_value", result.last_value);
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(106, "qualified_name", result.qualified_name, QualifiedName());
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALUseTable::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "table", LegacyTable());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
}

WALUseTable WALUseTable::Deserialize(Deserializer &deserializer) {
	WALUseTable result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto table = deserializer.ReadPropertyWithDefault<Identifier>(102, "table");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(table));
	}
	return result;
}

} // namespace duckdb
